### ISSUE TITLE
У МЕНЯ НЕ ЗАРАБОТАЛА ИГРА

### ISSUE THREAD

**Issue by Lamenich** [modeosr/srceng_launcher#2]
Я ЗАПУСТИЛ ЭТОТ ЛАУНЧЕР НА SAMSUNG GALAXY 7A PRO EDITION (2077), И У МЕНЯ СРАЗУ ДЫМОМ ПОШЁЛ. НАВЕРНОЕ ЭТО ЕМУ НУЖЕН БЫЛ DIRECT X 228.1 И WINE 1337 ((((

**Comment by ItzVladik** [comment]
попробуй перезагрузить телефон

**Comment by Lamenich** [comment]
СИЙЧАС!!!

**Comment by Lamenich** [comment]
ВСЁ РАВНО ПЫЛИТСЯ((((
ТЕПЕРЬ И ОГОНЬ ПОШЁЛ((((

**Comment by Lamenich** [comment]
HUGOSHADY СПАСИБО ЗА ФИКС ВАЙНА
ТЕПЕР Я В ДЕТДОМЕ С МОДЕЕЙ

**Comment by modeosr** [comment]
Не страдайте фигнёй, а запуск роботает только тогда когда вы соберёте сырой кусочек дерьма
